// src/enums/AssuntosEnum.js

const AssuntosEnum = Object.freeze([
	{ id: 10894, descricao: 'Abuso de Poder' },
    { id: 10364, descricao: 'Advertência / Repreensão' },
    { id: 3559, descricao: 'Advocacia administrativa' },
    { id: 8961, descricao: 'Antecipação de Tutela / Tutela Específica' },
    { id: 11291, descricao: 'Art. 150, CPM - Organização de grupo para prática de violência' },
    { id: 11303, descricao: 'Art. 155, CPM - Incitamento' },
    { id: 11276, descricao: 'Art. 157, CPM - Violência contra superior' },
    { id: 11275, descricao: 'Art. 158, CPM - Violência contra militar de serviço' },
    { id: 11307, descricao: 'Art. 160, CPM - Desrespeito a superior' },
    { id: 11304, descricao: 'Art. 162, CPM - Despojamento desprezível' },
    { id: 11295, descricao: 'Art. 163, CPM - Recusa a obediência' },
    { id: 11293, descricao: 'Art. 164, CPM - Oposição a ordem de sentinela' },
    { id: 11294, descricao: 'Art. 166, CPM - Publicação ou crítica indevida' },
    { id: 11286, descricao: 'Art. 175, CPM - Violência contra inferior' },
    { id: 11287, descricao: 'Art. 177, CPM - Resistência mediante ameaça ou violência' },
    { id: 11127, descricao: 'Art. 187, CPM - Deserção' },
    { id: 11135, descricao: 'Art. 195, CPM - Abandono de posto' },
    { id: 11136, descricao: 'Art. 196, CPM - Descumprimento de missão' },
    { id: 11138, descricao: 'Art. 202, CPM - Embriaguez em serviço' },
    { id: 11137, descricao: 'Art. 203, CPM - Dormir em serviço' },
    { id: 11125, descricao: 'Art. 204, CPM - Exercício de comércio por oficial' },
    { id: 11243, descricao: 'Art. 205, CPM - Homicídio' },
    { id: 11244, descricao: 'Art. 205, § 2º, CPM - Homicidio qualificado' },
    { id: 11238, descricao: 'Art. 209, CPM - Lesão leve' },
    { id: 11241, descricao: 'Art. 209, § 3º-A, CPM - Lesão seguida de morte' },
    { id: 11237, descricao: 'Art. 209, §§ 1º e 2º, CPM - Lesão grave' },
    { id: 11262, descricao: 'Art. 214, CPM - Calúnia' },
    { id: 11263, descricao: 'Art. 215, CPM - Difamação' },
    { id: 11264, descricao: 'Art. 216, CPM - Injúria' },
    { id: 11265, descricao: 'Art. 217, CPM - Injuria real' },
    { id: 11254, descricao: 'Art. 222, CPM - Constrangimento ilegal' },
    { id: 11253, descricao: 'Art. 223, CPM - Ameaça' },
    { id: 11257, descricao: 'Art. 225, CPM - Sequestro ou cárcere privado' },
    { id: 11259, descricao: 'Art. 226, CPM - Violação de domicílio' },
    { id: 11252, descricao: 'Art. 235, CPM - Ato Libidinoso' },
    { id: 11163, descricao: 'Art. 240, CPM - Furto' },
    { id: 11165, descricao: 'Art. 240, §§ 4º, 5º,  6º e 6º-A, CPM - Furto qualificado' },
    { id: 11164, descricao: 'Art. 241, CPM - Furto de uso' },
    { id: 11160, descricao: 'Art. 242, CPM - Roubo' },
    { id: 11156, descricao: 'Art. 243, CPM - Extorsão' },
    { id: 11167, descricao: 'Art. 251, CPM - Estelionato' },
    { id: 11173, descricao: 'Art. 259, CPM - Dano simples' },
    { id: 11172, descricao: 'Art. 261, CPM - Dano qualificado' },
    { id: 11171, descricao: 'Art. 262, CPM - Dano material ou aparelhamento de guerra' },
    { id: 11197, descricao: 'Art. 284, CPM - Atentado contra viatura ou outro meio de transporte' },
    { id: 11198, descricao: 'Art. 288, CPM - Interrupção ou perturbação de serviço ou meio de comunicação' },
    { id: 11207, descricao: 'Art. 290, CPM - Tráfico, posse ou uso de entorpecente ou substância de efeito similar' },
    { id: 11328, descricao: 'Art. 298, CPM - Desacato a superior' },
    { id: 11327, descricao: 'Art. 299, CPM - Desacato a militar' },
    { id: 11329, descricao: 'Art. 301, CPM - Desobediência' },
    { id: 11315, descricao: 'Art. 303, CPM - Peculato' },
    { id: 11317, descricao: 'Art. 303, § 2º, CPM - Peculato-furto' },
    { id: 11355, descricao: 'Art. 305, CPM - Concussão' },
    { id: 11353, descricao: 'Art. 308, CPM - Corrupção passiva' },
    { id: 11352, descricao: 'Art. 309, CPM - Corrupção ativa' },
    { id: 11322, descricao: 'Art. 311, CPM - Falsificação de documento' },
    { id: 11321, descricao: 'Art. 312, CPM - Falsidade ideológica' },
    { id: 11324, descricao: 'Art. 315, CPM - Uso de documento falso' },
    { id: 11323, descricao: 'Art. 316, CPM - Supressão de documento' },
    { id: 11320, descricao: 'Art. 318, CPM - Falsa identidade' },
    { id: 11346, descricao: 'Art. 319, CPM - Prevaricação' },
    { id: 11341, descricao: 'Art. 321, CPM - Extravio, sonegação ou inutilização de livro ou documento' },
    { id: 11339, descricao: 'Art. 322, CPM - Condescendência criminosa' },
    { id: 11342, descricao: 'Art. 324, CPM - Inobservancia de lei, regulamento ou instrução' },
    { id: 11348, descricao: 'Art. 326, CPM - Violação de sigilo funcional' },
    { id: 11351, descricao: 'Art. 333, CPM - Violência arbitrária' },
    { id: 11359, descricao: 'Art. 342, CPM - Coação' },
    { id: 11362, descricao: 'Art. 343, CPM - Denunciação caluniosa' },
    { id: 11360, descricao: 'Art. 344, CPM - Comunicação falsa de crime' },
    { id: 11367, descricao: 'Art. 346, CPM - Falso testemunho ou falsa perícia' },
    { id: 11370, descricao: 'Art. 352, CPM - Inutilização,onegação ou descaminho de material probante' },
    { id: 11365, descricao: 'Art. 354, CPM - Desobediência a decisão sobre perda ou suspensão de atividade ou direito' },
    { id: 5851, descricao: 'Assédio Sexual' },
    { id: 14685, descricao: 'Associação Criminosa' },
    { id: 5897, descricao: 'Associação para a Produção e Tráfico e Condutas Afins' },
    { id: 11249, descricao: 'Atentado violento ao pudor' },
    { id: 3395, descricao: 'Calúnia' },
    { id: 9517, descricao: 'Causas Supervenientes à Sentença' },
    { id: 10606, descricao: 'Cerceamento de Defesa' },
    { id: 3580, descricao: 'Coação no curso do processo' },
    { id: 5899, descricao: 'Colaboração com Grupo, Organização ou Associação Destinados à Produção ou Tráfico de Drogas' },
    { id: 10899, descricao: 'Competência da Justiça Estadual' },
    { id: 3401, descricao: 'Constrangimento Ilegal' },
    { id: 3555, descricao: 'Corrupção Passiva' },
    { id: 10950, descricao: 'Crime / Contravenção contra Criança / Adolescente' },
    { id: 11069, descricao: 'Crime Culposo' },
    { id: 11071, descricao: 'Crime Tentado' },
    { id: 3605, descricao: 'Crimes contra a Economia Popular' },
    { id: 3606, descricao: 'Crimes de Abuso de Autoridade' },
    { id: 15397, descricao: 'Crimes de Abuso de Autoridade (Lei 13.869/2019)' },
    { id: 3631, descricao: 'Crimes de Tortura' },
    { id: 3632, descricao: 'Crimes de Trânsito' },
    { id: 3633, descricao: 'Crimes do Sistema Nacional de Armas' },
    { id: 3637, descricao: 'Crimes Previstos no Estatuto da criança e do adolescente' },
    { id: 4703, descricao: 'Defeito, nulidade ou anulação' },
    { id: 3576, descricao: 'Denunciação caluniosa' },
    { id: 7940, descricao: 'Deserção' },
    { id: 3396, descricao: 'Difamação' },
    { id: 9893, descricao: 'Do sistema nacional de armas' },
    { id: 9047, descricao: 'Efeitos' },
    { id: 11797, descricao: 'Entrada de aparelho telefônico de comunicação móvel em estabelecimento prisional' },
    { id: 9895, descricao: 'Estatuto da criança e do adolescente' },
    { id: 11417, descricao: 'Estupro de Vulnerável' },
    { id: 3585, descricao: 'Exercício arbitrário ou abuso de poder' },
    { id: 3533, descricao: 'Falsidade Ideológica' },
    { id: 3582, descricao: 'Fraude Processual' },
    { id: 5556, descricao: 'Grave' },
    { id: 10891, descricao: 'Habeas Corpus - Cabimento' },
    { id: 3370, descricao: 'Homicídio simples' },
    { id: 12397, descricao: 'Importunação sexual' },
    { id: 11101, descricao: 'Indulto' },
    { id: 10009, descricao: 'Inquérito / Processo / Recurso Administrativo' },
    { id: 15128, descricao: 'Intolerância e/ou Injúria Racial, de Cor e/ou Etnia' },
    { id: 12352, descricao: 'Jogo do bicho' },
    { id: 12350, descricao: 'Jogos de azar' },
    { id: 10982, descricao: 'Lavagem ou Ocultação de Bens, Direitos ou Valores Oriundos de Corrupção' },
    { id: 13004, descricao: 'Legitimidade - Autoridade Coatora' },
    { id: 7928, descricao: 'Liberdade Provisória' },
    { id: 10366, descricao: 'Licenciamento / Exclusão' },
    { id: 14782, descricao: 'Maus tratos' },
    { id: 10023, descricao: 'Multas e demais Sanções' },
    { id: 3392, descricao: 'Omissão de socorro' },
    { id: 7791, descricao: 'Pena Privativa de Liberdade' },
    { id: 11096, descricao: 'Perda da Graduação das Praças' },
    { id: 11097, descricao: 'Perda do Posto e da Patente' },
    { id: 3390, descricao: 'Perigo para a vida ou saúde de outrem' },
    { id: 14684, descricao: 'Perseguição' },
    { id: 11103, descricao: 'Prescrição' },
    { id: 3557, descricao: 'Prevaricação' },
    { id: 10904, descricao: 'Prisão Domiciliar / Especial' },
    { id: 4355, descricao: 'Prisão Preventiva' },
    { id: 14238, descricao: 'Produção Antecipada de Provas' },
    { id: 12334, descricao: 'Promoção, constituição, financiamento ou integração de Organização Criminosa' },
    { id: 10328, descricao: 'Reintegração' },
    { id: 11064, descricao: 'Representação do Corregedor' },
    { id: 11065, descricao: 'Requerimento da Parte' },
    { id: 12544, descricao: 'Simples' },
    { id: 4271, descricao: 'Suspensão' },
    { id: 10367, descricao: 'Suspensão' },
    { id: 11087, descricao: 'Suspensão Condicional da Pena' },
    { id: 3608, descricao: 'Tráfico de drogas e Condutas Afins' },
    { id: 9859, descricao: 'Tráfico de Drogas e Condutas Afins' },
    { id: 4272, descricao: 'Trancamento' },
    { id: 10610, descricao: 'Trancamento' },
    { id: 12345, descricao: 'Vias de fato' },
    { id: 3563, descricao: 'Violação do sigilo funcional' },
    { id: 3560, descricao: 'Violência arbitrária (art. 322)' },
    { id: 14942, descricao: 'Violência Psicológica contra a Mulher' },
]);

export default AssuntosEnum;
