// src/enums/AssuntosEnum.js

const AssuntosEnum = Object.freeze([
	{ id: 11120, descricao: 'Art. 184, CPM - Criação ou simulação de incapacidade física'},
	{ id: 11121, descricao: 'Art. 186, CPM - Favorecimento a convocado'},
	{ id: 11122, descricao: 'Art. 183, CPM - Insubmissão'},
	{ id: 11123, descricao: 'Art. 183, § 2º, CPM - Insubmissão privilegiada'},
	{ id: 11124, descricao: 'Art. 185, CPM - Substituição de convocado'},
	{ id: 11125, descricao: 'Art. 204, CPM - Exercício de comércio por oficial'},
	{ id: 11126, descricao: 'Art. 191, CPM - Concerto para deserção'},
	{ id: 11127, descricao: 'Art. 187, CPM - Deserção'},
	{ id: 11128, descricao: 'Art. 188, CPM - Deserção - casos assimilados'},
	{ id: 11129, descricao: 'Art. 190, CPM - Deserção especial'},
	{ id: 11130, descricao: 'Art. 192, CPM - Deserção por evasão ou fuga'},
	{ id: 11131, descricao: 'Art. 189, inciso I, CPM - Deserção privilegiada'},
	{ id: 11132, descricao: 'Art. 189, inciso II, CPM - Deserção qualificada'},
	{ id: 11133, descricao: 'Art. 193, CPM - Favorecimento a desertor'},
	{ id: 11134, descricao: 'Art. 194, CPM - Omissão de Oficial'},
	{ id: 11135, descricao: 'Art. 195, CPM - Abandono de posto'},
	{ id: 11136, descricao: 'Art. 196, CPM - Descumprimento de missão'},
	{ id: 11137, descricao: 'Art. 203, CPM - Dormir em serviço'},
	{ id: 11138, descricao: 'Art. 202, CPM - Embriaguez em serviço'},
	{ id: 11139, descricao: 'Art. 198, CPM - Omissão de eficiência da força'},
	{ id: 11140, descricao: 'Art. 199, CPM - Omissão de providências para evitar danos'},
	{ id: 11141, descricao: 'Art. 200, CPM - Omissão de providências para salvar comandados'},
	{ id: 11142, descricao: 'Art. 201, CPM - Omissão de socorro'},
	{ id: 11143, descricao: 'Art. 197, CPM - Retenção indevida'},
	{ id: 11152, descricao: 'Art. 257, CPM - Alteração de Limites'},
	{ id: 11153, descricao: 'Art. 258, CPM - Aposição, supressão ou alteração de marca'},
	{ id: 11154, descricao: 'Art. 267, CPM - Usura pecuniária'},
	{ id: 11155, descricao: 'Art. 245, CPM - Chantagem'},
	{ id: 11156, descricao: 'Art. 243, CPM - Extorsão'},
	{ id: 11157, descricao: 'Art. 246, CPM - Extorsão indireta'},
	{ id: 11158, descricao: 'Art. 244, CPM - Extorsão mediante sequestro'},
	{ id: 11159, descricao: 'Art. 242, § 3º, CPM - Latrocínio'},
	{ id: 11160, descricao: 'Art. 242, CPM - Roubo'},
	{ id: 11161, descricao: 'Art. 242, § 2º, CPM - Roubo qualificado'},
	{ id: 11162, descricao: 'Art. 254, CPM - Receptação'},
	{ id: 11163, descricao: 'Art. 240, CPM - Furto'},
	{ id: 11164, descricao: 'Art. 241, CPM - Furto de uso'},
	{ id: 11165, descricao: 'Art. 240, §§ 4º, 5º,  6º e 6º-A, CPM - Furto qualificado'},
	{ id: 11166, descricao: 'Art. 252, CPM - Abuso de pessoa'},
	{ id: 11167, descricao: 'Art. 251, CPM - Estelionato'},
	{ id: 11168, descricao: 'Art. 260, CPM - Dano atenuado'},
	{ id: 11169, descricao: 'Art. 264, CPM - Dano em aparelhos e instalações'},
	{ id: 11170, descricao: 'Art. 263, CPM - Dano em navio de guerra ou mercante em serviço militar'},
	{ id: 11171, descricao: 'Art. 262, CPM - Dano material ou aparelhamento de guerra'},
	{ id: 11172, descricao: 'Art. 261, CPM - Dano qualificado'},
	{ id: 11173, descricao: 'Art. 259, CPM - Dano simples'},
	{ id: 11174, descricao: 'Art. 265, CPM - Desaparecimento,consunção ou extravio'},
	{ id: 11175, descricao: 'Art. 249, parágrafo único, CPM - Apropriação de coisa achada'},
	{ id: 11176, descricao: 'Art. 249, CPM - Apropriação de coisa havida acidentalmente'},
	{ id: 11177, descricao: 'Art. 248, CPM - Apropriação indébita'},
	{ id: 11181, descricao: 'Art. 271, CPM - Abuso de radiação'},
	{ id: 11182, descricao: 'Art. 274, CPM - Desabamento ou desmoronamento'},
	{ id: 11183, descricao: 'Art. 278, CPM - Difusão de epizootia ou praga vegetal'},
	{ id: 11184, descricao: 'Art. 279, CPM - Embriaguez ao volante'},
	{ id: 11185, descricao: 'Art. 270, CPM - Emprego de gás tóxico ou asfixiante'},
	{ id: 11186, descricao: 'Art. 269, CPM - Explosão'},
	{ id: 11187, descricao: 'Art. 276, CPM - Fatos que expõem a perigo aparelhamento militar'},
	{ id: 11188, descricao: 'Art. 281, CPM - Fuga após acidente de trânsito'},
	{ id: 11189, descricao: 'Art. 268, CPM - Incêndio'},
	{ id: 11190, descricao: 'Art. 272, CPM - Inundação'},
	{ id: 11191, descricao: 'Art. 273, CPM - Perigo de inundação'},
	{ id: 11192, descricao: 'Art. 280, CPM - Perigo resultante de violação de regra de trânsito'},
	{ id: 11193, descricao: 'Art. 275, CPM - Subtração, ocultação ou inutilização de material de socorro'},
	{ id: 11194, descricao: 'Art. 286, CPM - Arremesso de projétil'},
	{ id: 11195, descricao: 'Art. 287, CPM - Atentado contra serviço de utilidade militar'},
	{ id: 11196, descricao: 'Art. 283, CPM - Atentado contra transporte'},
	{ id: 11197, descricao: 'Art. 284, CPM - Atentado contra viatura ou outro meio de transporte'},
	{ id: 11198, descricao: 'Art. 288, CPM - Interrupção ou perturbação de serviço ou meio de comunicação'},
	{ id: 11199, descricao: 'Art. 282, CPM - Perigo de desastre ferroviário'},
	{ id: 11200, descricao: 'Art. 294, CPM - Corrupção ou poluição de água potável'},
	{ id: 11201, descricao: 'Art. 293, CPM - Envenenamento com perigo extensivo'},
	{ id: 11202, descricao: 'Art. 292, CPM - Epidemia'},
	{ id: 11203, descricao: 'Art. 296, CPM - Fornecimento de substância alterada'},
	{ id: 11204, descricao: 'Art. 295, CPM - Fornecimento de substancia nociva'},
	{ id: 11205, descricao: 'Art. 297, CPM - Omissão de notificação de doença'},
	{ id: 11206, descricao: 'Art. 291, CPM - Receita Ilegal'},
	{ id: 11207, descricao: 'Art. 290, CPM - Tráfico, posse ou uso de entorpecente ou substância de efeito similar'},
	{ id: 11208, descricao: 'Art. 138, CPM - Ato de jurisdição indevida'},
	{ id: 11209, descricao: 'Art. 143, CPM - Consecução de notícia, informação ou documento para fim de espionagem'},
	{ id: 11210, descricao: 'Art. 147, CPM - Desenho ou levantamento de plano ou planta de local militar'},
	{ id: 11211, descricao: 'Art. 140, CPM - Entendimento para empenhar o Brasil à neutralidade ou à guerra'},
	{ id: 11212, descricao: 'Art. 141, CPM - Entendimento para gerar conflito ou divergência com o Brasil'},
	{ id: 11213, descricao: 'Art. 136, CPM - Hostilidade contra país estrangeiro'},
	{ id: 11214, descricao: 'Art. 136, § 1º, CPM - Hostilidade qualificada pelo resultado'},
	{ id: 11215, descricao: 'Art. 146, CPM - Penetração com o fim de espionagem'},
	{ id: 11216, descricao: 'Art. 137, CPM - Provocação a país estrangeiro'},
	{ id: 11217, descricao: 'Art. 144, CPM - Revelação de notícia, informação ou documento'},
	{ id: 11218, descricao: 'Art. 144, § 1º, CPM - Revelação de notícia, informação ou documento, com o fim de espionagem militar'},
	{ id: 11219, descricao: 'Art. 148, CPM - Sobrevôo em local interdito'},
	{ id: 11220, descricao: 'Art. 142, CPM - Tentativa contra a soberania do Brasil'},
	{ id: 11221, descricao: 'Art. 145, CPM - Turbação de objeto ou documento'},
	{ id: 11222, descricao: 'Art. 139, CPM - Violação de território estrangeiro'},
	{ id: 11231, descricao: 'Art. 238, CPM - Ato obsceno'},
	{ id: 11232, descricao: 'Art. 239, CPM - Escrito ou objeto obsceno'},
	{ id: 11233, descricao: 'Art. 212, CPM - Abandono de pessoa'},
	{ id: 11234, descricao: 'Art. 212, §§ 1º e 2º, CPM - Abandono de pessoa seguida de morte ou lesão grave'},
	{ id: 11235, descricao: 'Art. 213, CPM - Maus tratos'},
	{ id: 11236, descricao: 'Art. 213, §§ 1º e 2º, CPM - Maus tratos seguido de morte ou lesão grave'},
	{ id: 11237, descricao: 'Art. 209, §§ 1º e 2º, CPM - Lesão grave'},
	{ id: 11238, descricao: 'Art. 209, CPM - Lesão leve'},
	{ id: 11239, descricao: 'Art. 209, § 6º, CPM - Lesão levíssima'},
	{ id: 11240, descricao: 'Art. 209, § 4º, CPM - Lesão privilegiada'},
	{ id: 11241, descricao: 'Art. 209, § 3º-A, CPM - Lesão seguida de morte'},
	{ id: 11242, descricao: 'Art. 211, CPM - Participação em rixa'},
	{ id: 11243, descricao: 'Art. 205, CPM - Homicídio'},
	{ id: 11244, descricao: 'Art. 205, § 2º, CPM - Homicidio qualificado'},
	{ id: 11245, descricao: 'Art. 205, § 1º, CPM - Homicídio privilegiado'},
	{ id: 11246, descricao: 'Art. 207, CPM - Provocação direta ou auxílio a suicídio'},
	{ id: 11247, descricao: 'Art. 207, § 2º, CPM - Provocação indireta ao suicídio'},
	{ id: 11248, descricao: 'Art. 208, CPM - Genocídio'},
	{ id: 11251, descricao: 'Art. 232, CPM - Estupro'},
	{ id: 11252, descricao: 'Art. 235, CPM - Ato Libidinoso'},
	{ id: 11253, descricao: 'Art. 223, CPM - Ameaça'},
	{ id: 11254, descricao: 'Art. 222, CPM - Constrangimento ilegal'},
	{ id: 11255, descricao: 'Art. 224, CPM - Desafio para duelo'},
	{ id: 11256, descricao: 'Art. 228, CPM - Divulgação de segredo'},
	{ id: 11257, descricao: 'Art. 225, CPM - Sequestro ou cárcere privado'},
	{ id: 11258, descricao: 'Art. 227, CPM - Violação de correspondência'},
	{ id: 11259, descricao: 'Art. 226, CPM - Violação de domicílio'},
	{ id: 11260, descricao: 'Art. 229, CPM - Violação de recato'},
	{ id: 11261, descricao: 'Art. 230, CPM - Violação de segredo profissional'},
	{ id: 11262, descricao: 'Art. 214, CPM - Calúnia'},
	{ id: 11263, descricao: 'Art. 215, CPM - Difamação'},
	{ id: 11264, descricao: 'Art. 216, CPM - Injúria'},
	{ id: 11265, descricao: 'Art. 217, CPM - Injuria real'},
	{ id: 11266, descricao: 'Art. 219, CPM - Ofensa às forças armadas'},
	{ id: 11275, descricao: 'Art. 158, CPM - Violência contra militar de serviço'},
	{ id: 11276, descricao: 'Art. 157, CPM - Violência contra superior'},
	{ id: 11277, descricao: 'Art. 173, CPM - Abuso de requisição militar'},
	{ id: 11278, descricao: 'Art. 167, CPM - Assunção de comando sem ordem ou autorização'},
	{ id: 11279, descricao: 'Art. 168, CPM - Conservação ilegal de comando'},
	{ id: 11280, descricao: 'Art. 176, CPM - Ofensa aviltante a inferior'},
	{ id: 11281, descricao: 'Art. 169, CPM - Operação militar sem ordem superior'},
	{ id: 11282, descricao: 'Art. 170, CPM - Ordem arbitrária de invasão'},
	{ id: 11283, descricao: 'Art. 174, CPM - Rigor excessivo'},
	{ id: 11284, descricao: 'Art. 172, CPM - Uso indevido de uniforme, distintivo ou insígnia militar por qualquer pessoa'},
	{ id: 11285, descricao: 'Art. 171, CPM - Uso indevido por militar de uniforme, distintivo ou insígnia'},
	{ id: 11286, descricao: 'Art. 175, CPM - Violência contra inferior'},
	{ id: 11287, descricao: 'Art. 177, CPM - Resistência mediante ameaça ou violência'},
	{ id: 11288, descricao: 'Art. 152, CPM - Conspiração'},
	{ id: 11289, descricao: 'Art. 149, CPM - Motim'},
	{ id: 11290, descricao: 'Art. 151, CPM - Omissão de lealdade militar'},
	{ id: 11291, descricao: 'Art. 150, CPM - Organização de grupo para prática de violência'},
	{ id: 11292, descricao: 'Art. 149, parágrafo único, CPM - Revolta'},
	{ id: 11293, descricao: 'Art. 164, CPM - Oposição a ordem de sentinela'},
	{ id: 11294, descricao: 'Art. 166, CPM - Publicação ou crítica indevida'},
	{ id: 11295, descricao: 'Art. 163, CPM - Recusa a obediência'},
	{ id: 11296, descricao: 'Art. 165, CPM - Reunião ilícita'},
	{ id: 11297, descricao: 'Art. 182, CPM - Amotinamento'},
	{ id: 11298, descricao: 'Art. 181, CPM - Arrebatamento de preso ou internado'},
	{ id: 11299, descricao: 'Art. 180, CPM - Evasão de preso ou internado'},
	{ id: 11300, descricao: 'Art. 178, CPM - Fuga de preso ou internado'},
	{ id: 11301, descricao: 'Art. 154, CPM - Aliciação para motim ou revolta'},
	{ id: 11302, descricao: 'Art. 156, CPM - Apologia de fato criminoso ou do seu autor'},
	{ id: 11303, descricao: 'Art. 155, CPM - Incitamento'},
	{ id: 11304, descricao: 'Art. 162, CPM - Despojamento desprezível'},
	{ id: 11305, descricao: 'Art. 160, parágrafo único, CPM - Desrespeito a comandante, oficial-general ou oficial de serviço'},
	{ id: 11306, descricao: 'Art. 161, CPM - Desrespeito a símbolo nacional'},
	{ id: 11307, descricao: 'Art. 160, CPM - Desrespeito a superior'},
	{ id: 11315, descricao: 'Art. 303, CPM - Peculato'},
	{ id: 11316, descricao: 'Art. 304, CPM - Peculato mediante aproveitamento ou erro de outrem'},
	{ id: 11317, descricao: 'Art. 303, § 2º, CPM - Peculato-furto'},
	{ id: 11318, descricao: 'Art. 314, CPM - Certidão ou atestado ideologicamente falso'},
	{ id: 11319, descricao: 'Art. 313, CPM - Cheques sem fundos'},
	{ id: 11320, descricao: 'Art. 318, CPM - Falsa identidade'},
	{ id: 11321, descricao: 'Art. 312, CPM - Falsidade ideológica'},
	{ id: 11322, descricao: 'Art. 311, CPM - Falsificação de documento'},
	{ id: 11323, descricao: 'Art. 316, CPM - Supressão de documento'},
	{ id: 11324, descricao: 'Art. 315, CPM - Uso de documento falso'},
	{ id: 11325, descricao: 'Art. 317, CPM - Uso de documento pessoal alheio'},
	{ id: 11326, descricao: 'Art. 300, CPM - Desacato a assemelhado ou funcionário'},
	{ id: 11327, descricao: 'Art. 299, CPM - Desacato a militar'},
	{ id: 11328, descricao: 'Art. 298, CPM - Desacato a superior'},
	{ id: 11329, descricao: 'Art. 301, CPM - Desobediência'},
	{ id: 11330, descricao: 'Art. 302, CPM - Ingresso clandestino'},
	{ id: 11331, descricao: 'Art. 339, CPM - Impedimento, perturbação ou fraude de concorrencia'},
	{ id: 11332, descricao: 'Art. 338, CPM - Inutilização de edital ou de sinal oficial'},
	{ id: 11333, descricao: 'Art. 337, CPM - Subtração ou inutilização de livro, processo ou documento'},
	{ id: 11334, descricao: 'Art. 336, CPM - Tráfico de influência'},
	{ id: 11335, descricao: 'Art. 335, CPM - Usurpação de função'},
	{ id: 11336, descricao: 'Art. 330, CPM - Abandono de cargo'},
	{ id: 11337, descricao: 'Art. 332, CPM - Abuso de confiança ou boa fé'},
	{ id: 11338, descricao: 'Art. 331, CPM - Aplicação ilegal de verba ou dinheiro'},
	{ id: 11339, descricao: 'Art. 322, CPM - Condescendência criminosa'},
	{ id: 11340, descricao: 'Art. 329, CPM - Exercício funcional ilegal'},
	{ id: 11341, descricao: 'Art. 321, CPM - Extravio, sonegação ou inutilização de livro ou documento'},
	{ id: 11342, descricao: 'Art. 324, CPM - Inobservancia de lei, regulamento ou instrução'},
	{ id: 11343, descricao: 'Art. 323, CPM - Não inclusão de nome em lista'},
	{ id: 11344, descricao: 'Art. 328, CPM - Obstáculo à hasta pública, concorrência ou tomada de preços'},
	{ id: 11345, descricao: 'Art. 334, CPM - Patrocínio indébito'},
	{ id: 11346, descricao: 'Art. 319, CPM - Prevaricação'},
	{ id: 11347, descricao: 'Art. 327, CPM - Violação de sigilo de proposta de concorrência'},
	{ id: 11348, descricao: 'Art. 326, CPM - Violação de sigilo funcional'},
	{ id: 11349, descricao: 'Art. 320, CPM - Violação do dever funcional com o fim de lucro'},
	{ id: 11350, descricao: 'Art. 325, CPM - Violação ou divulgação indevida de correspondência ou comunicação'},
	{ id: 11351, descricao: 'Art. 333, CPM - Violência arbitrária'},
	{ id: 11352, descricao: 'Art. 309, CPM - Corrupção ativa'},
	{ id: 11353, descricao: 'Art. 308, CPM - Corrupção passiva'},
	{ id: 11354, descricao: 'Art. 310, CPM - Participação ilícita'},
	{ id: 11355, descricao: 'Art. 305, CPM - Concussão'},
	{ id: 11356, descricao: 'Art. 307, CPM - Desvio'},
	{ id: 11357, descricao: 'Art. 306, CPM - Excesso de exação'},
	{ id: 11358, descricao: 'Art. 345, CPM - Auto-acusação falsa'},
	{ id: 11359, descricao: 'Art. 342, CPM - Coação'},
	{ id: 11360, descricao: 'Art. 344, CPM - Comunicação falsa de crime'},
	{ id: 11361, descricao: 'Art. 347, CPM - Corrupção ativa de testemunha, perito ou intérprete'},
	{ id: 11362, descricao: 'Art. 343, CPM - Denunciação caluniosa'},
	{ id: 11363, descricao: 'Art. 341, CPM - Desacato'},
	{ id: 11364, descricao: 'Art. 349, CPM - Desobediência a decisão judicial'},
	{ id: 11365, descricao: 'Art. 354, CPM - Desobediência a decisão sobre perda ou suspensão de atividade ou direito'},
	{ id: 11366, descricao: 'Art. 353, CPM - Exploração de prestígio'},
	{ id: 11367, descricao: 'Art. 346, CPM - Falso testemunho ou falsa perícia'},
	{ id: 11368, descricao: 'Art. 350, CPM - Favorecimento pessoal'},
	{ id: 11369, descricao: 'Art. 351, CPM - Favorecimento real'},
	{ id: 11370, descricao: 'Art. 352, CPM - Inutilização,onegação ou descaminho de material probante'},
	{ id: 11371, descricao: 'Art. 348, CPM - Publicidade opressiva'},
	{ id: 11372, descricao: 'Art. 340, CPM - Recusa de função na Justiça Militar'},
    { id: 11116, descricao: 'Abandono de posto e de outros crimes em serviço'},
    { id: 11089, descricao: 'Abolitio criminis'},
    { id: 10894, descricao: 'Abuso de Poder'},
    { id: 2569, descricao: 'Acidente de Trabalho'},
    { id: 8809, descricao: 'Acidente de Trabalho'},
    { id: 10737, descricao: 'Adequação da Ação / Procedimento'},
    { id: 10364, descricao: 'Advertência / Repreensão'},
    { id: 3559, descricao: 'Advocacia administrativa'},
    { id: 10189, descricao: 'Afastamento'},
    { id: 10186, descricao: 'Agentes Políticos'},
    { id: 11268, descricao: 'Aliciação e incitamento'},
    { id: 15037, descricao: 'Alvará de Soltura'},
    { id: 3402, descricao: 'Ameaça'},
    { id: 9661, descricao: 'Ameaça'},
    { id: 11100, descricao: 'Anistia'},
    { id: 8961, descricao: 'Antecipação de Tutela / Tutela Específica'},
    { id: 10382, descricao: 'Anulação'},
    { id: 10379, descricao: 'Anulação e Correção de Provas / Questões'},
    { id: 11081, descricao: 'Aplicação da Pena'},
    { id: 5870, descricao: 'Apologia de crime ou criminoso'},
    { id: 10191, descricao: 'Aposentadoria'},
    { id: 11144, descricao: 'Apropriação Indébita'},
    { id: 12640, descricao: 'Arquivamento de Procedimento Investigatório Criminal - PIC-MP'},
    { id: 8843, descricao: 'Assistência Judiciária Gratuita'},
    { id: 14685, descricao: 'Associação Criminosa'},
    { id: 5897, descricao: 'Associação para a Produção e Tráfico e Condutas Afins'},
    { id: 5851, descricao: 'Assédio Sexual'},
    { id: 11249, descricao: 'Atentado violento ao pudor'},
    { id: 4701, descricao: 'Ato / Negócio Jurídico'},
    { id: 9520, descricao: 'Ato Atentatório à Dignidade da Justiça'},
    { id: 9634, descricao: 'Ato Infracional'},
    { id: 9997, descricao: 'Atos Administrativos'},
    { id: 11786, descricao: 'Atos executórios'},
    { id: 8893, descricao: 'Atos Processuais'},
    { id: 10867, descricao: 'Ausência de Fundamentação'},
    { id: 10866, descricao: 'Ausência de Publicidade'},
    { id: 12955, descricao: 'Autenticação'},
    { id: 3578, descricao: 'Auto-acusação falsa'},
    { id: 12754, descricao: 'Auxílio Emergencial (Lei 13.982/2020)'},
    { id: 14959, descricao: 'Avaliação e Venda em Leilão Público'},
    { id: 4263, descricao: 'Ação Penal'},
    { id: 11050, descricao: 'Ação Penal Militar'},
    { id: 15040, descricao: 'Busca e Apreensão'},
    { id: 10914, descricao: 'Busca e Apreensão de Bens'},
    { id: 9098, descricao: 'Cabimento'},
    { id: 3395, descricao: 'Calúnia'},
    { id: 9493, descricao: 'Capacidade Processual'},
    { id: 11058, descricao: 'Cassação de licença para direção de veículo motorizado'},
    { id: 9517, descricao: 'Causas Supervenientes à Sentença'},
    { id: 9532, descricao: 'Caução / Contracautela'},
    { id: 10606, descricao: 'Cerceamento de Defesa'},
    { id: 10865, descricao: 'Cerceamento de Defesa'},
    { id: 10938, descricao: 'Citação'},
    { id: 11783, descricao: 'Citação'},
    { id: 15034, descricao: 'Citação'},
    { id: 10381, descricao: 'Classificação e/ou Preterição'},
    { id: 3580, descricao: 'Coação no curso do processo'},
    { id: 5899, descricao: 'Colaboração com Grupo, Organização ou Associação Destinados à Produção ou Tráfico de Drogas'},
    { id: 12962, descricao: 'Competência'},
    { id: 8829, descricao: 'Competência '},
    { id: 10654, descricao: 'Competência da Justiça Estadual'},
    { id: 10899, descricao: 'Competência da Justiça Estadual'},
    { id: 10653, descricao: 'Competência da Justiça Federal'},
    { id: 10898, descricao: 'Competência da Justiça Federal'},
    { id: 11047, descricao: 'Competência da Justiça Militar da União'},
    { id: 11055, descricao: 'Competência da Justiça Militar da União'},
    { id: 11048, descricao: 'Competência da Justiça Militar dos Estados'},
    { id: 11056, descricao: 'Competência da Justiça Militar Estadual'},
    { id: 10651, descricao: 'Competência dos Juizados Especiais'},
    { id: 10897, descricao: 'Competência dos Juizados Especiais'},
    { id: 10900, descricao: 'Competência por Prerrogativa de Função'},
    { id: 10901, descricao: 'Competência por Prerrogativa de Função'},
    { id: 15044, descricao: 'Comunicação de Prisão - BNMP'},
    { id: 3577, descricao: 'Comunicação falsa de crime ou de contravenção'},
    { id: 9418, descricao: 'Concurso de Credores'},
    { id: 10370, descricao: 'Concurso Público / Edital'},
    { id: 11308, descricao: 'Concussão, Excesso de Exação e Desvio'},
    { id: 11059, descricao: 'Confisco'},
    { id: 13111, descricao: 'Conselhos Regionais de Fiscalização Profissional e Afins'},
    { id: 3401, descricao: 'Constrangimento Ilegal'},
    { id: 9660, descricao: 'Constrangimento ilegal'},
    { id: 9163, descricao: 'Constrição / Penhora / Avaliação / Indisponibilidade de Bens'},
    { id: 9740, descricao: 'Contra a dignidade sexual'},
    { id: 9879, descricao: 'Contra a fauna'},
    { id: 9807, descricao: 'Contra a fé pública'},
    { id: 9659, descricao: 'Contra a liberdade pessoal'},
    { id: 12194, descricao: 'Contra a mulher'},
    { id: 11178, descricao: 'Contra a Saúde'},
    { id: 9848, descricao: 'Contra o meio ambiente'},
    { id: 12195, descricao: 'Contra pessoas não identificadas como mulher'},
    { id: 3692, descricao: 'Contravenções Penais'},
    { id: 9914, descricao: 'Contravenções Penais'},
    { id: 11114, descricao: 'Conversão da Pena'},
    { id: 10999, descricao: 'Conversão em Agravo Retido'},
    { id: 11051, descricao: 'Correição Parcial'},
    { id: 10685, descricao: 'Correção Monetária'},
    { id: 11309, descricao: 'Corrupção'},
    { id: 11250, descricao: 'Corrupção de menores'},
    { id: 3555, descricao: 'Corrupção Passiva'},
    { id: 12612, descricao: 'COVID-19'},
    { id: 10950, descricao: 'Crime / Contravenção contra Criança / Adolescente'},
    { id: 10951, descricao: 'Crime / Contravenção contra idoso'},
    { id: 10986, descricao: 'Crime contra a administração ambiental'},
    { id: 3620, descricao: 'Crime contra a flora'},
    { id: 11069, descricao: 'Crime Culposo'},
    { id: 5555, descricao: 'Crime Tentado'},
    { id: 11071, descricao: 'Crime Tentado'},
    { id: 5874, descricao: 'Crimes Contra a Administração da Justiça'},
    { id: 11072, descricao: 'Crimes contra a Administração da Justiça Militar'},
    { id: 11073, descricao: 'Crimes contra a Administração Militar'},
    { id: 11074, descricao: 'Crimes contra a Autoridade ou Disciplina Militar'},
    { id: 3463, descricao: 'Crimes contra a Dignidade Sexual'},
    { id: 3605, descricao: 'Crimes contra a Economia Popular'},
    { id: 3619, descricao: 'Crimes contra a fauna'},
    { id: 3523, descricao: 'Crimes Contra a Fé Pública'},
    { id: 3394, descricao: 'Crimes contra a Honra'},
    { id: 11223, descricao: 'Crimes contra a Honra'},
    { id: 3491, descricao: 'Crimes contra a Incolumidade Pública'},
    { id: 3405, descricao: 'Crimes contra a inviolabilidade de domicílio'},
    { id: 3412, descricao: 'Crimes contra a inviolabilidade de segredo'},
    { id: 11224, descricao: 'Crimes contra a Liberdade'},
    { id: 3400, descricao: 'Crimes contra a liberdade pessoal'},
    { id: 3445, descricao: 'Crimes Contra a organização do trabalho'},
    { id: 3520, descricao: 'Crimes Contra a paz Pública'},
    { id: 11075, descricao: 'Crimes contra a Pessoa'},
    { id: 3369, descricao: 'Crimes contra a vida'},
    { id: 11077, descricao: 'Crimes contra Incolumidade Pública'},
    { id: 11310, descricao: 'Crimes contra o dever funcional'},
    { id: 3618, descricao: 'Crimes contra o Meio Ambiente e o Patrimônio Genético'},
    { id: 3415, descricao: 'Crimes Contra o Patrimônio'},
    { id: 11078, descricao: 'Crimes contra o Patrimônio'},
    { id: 3457, descricao: 'Crimes contra o sentimento religioso e contra o respeito aos mortos'},
    { id: 11079, descricao: 'Crimes contra o Serviço Militar e o Dever Militar'},
    { id: 11179, descricao: 'Crimes contra os Meios de Transporte e de Comunicação'},
    { id: 3606, descricao: 'Crimes de Abuso de Autoridade'},
    { id: 3628, descricao: 'Crimes de Lavagem ou Ocultação de Bens, Direitos ou Valores'},
    { id: 11180, descricao: 'Crimes de Perigo Comum'},
    { id: 15127, descricao: 'Crimes de Preconceito'},
    { id: 3631, descricao: 'Crimes de Tortura'},
    { id: 3607, descricao: 'Crimes de Tráfico Ilícito e Uso Indevido de Drogas'},
    { id: 3632, descricao: 'Crimes de Trânsito'},
    { id: 3633, descricao: 'Crimes do Sistema Nacional de Armas'},
    { id: 3547, descricao: 'Crimes Praticados por Funcionários Públicos Contra a Administração em Geral'},
    { id: 5872, descricao: 'Crimes praticados por particular contra a administração em geral'},
    { id: 11311, descricao: 'Crimes praticados por particular contra a Administração Militar'},
    { id: 3603, descricao: 'Crimes Previstos na Legislação Extravagante'},
    { id: 12333, descricao: 'Crimes previstos na Lei da Organização Criminosa'},
    { id: 3637, descricao: 'Crimes Previstos no Estatuto da criança e do adolescente'},
    { id: 3659, descricao: 'Crimes previstos no Estatuto do Idoso'},
    { id: 3613, descricao: 'Crimes Resultante de Preconceito de Raça ou de Cor'},
    { id: 11225, descricao: 'Crimes Sexuais'},
    { id: 10680, descricao: 'Crédito Complementar'},
    { id: 10658, descricao: 'Custas'},
    { id: 11145, descricao: 'Dano'},
    { id: 3426, descricao: 'Dano (Art. 163)'},
    { id: 10012, descricao: 'Dano ao Erário'},
    { id: 9858, descricao: 'De Tráfico Ilícito e Uso Indevido de Drogas'},
    { id: 5560, descricao: 'Decorrente de violência doméstica'},
    { id: 4703, descricao: 'Defeito, nulidade ou anulação'},
    { id: 7941, descricao: 'Denegação'},
    { id: 3576, descricao: 'Denunciação caluniosa'},
    { id: 4368, descricao: 'Denúncia/Queixa'},
    { id: 10940, descricao: 'Depoimento'},
    { id: 10860, descricao: 'Depositário Infiel'},
    { id: 12973, descricao: 'Depósito Prévio de Multa Administrativa'},
    { id: 3573, descricao: 'Desacato'},
    { id: 11312, descricao: 'Desacato e da Desobediência'},
    { id: 10631, descricao: 'Desaforamento'},
    { id: 10935, descricao: 'Desclassificação'},
    { id: 7940, descricao: 'Deserção'},
    { id: 11117, descricao: 'Deserção'},
    { id: 3572, descricao: 'Desobediência'},
    { id: 9925, descricao: 'Desobediência (art. 330)'},
    { id: 10523, descricao: 'Despenalização / Descriminalização'},
    { id: 11267, descricao: 'Desrespeito a superior e a símbolo nacional ou farda'},
    { id: 14881, descricao: 'Destinação de Bens e Mercadorias/Coisas Apreendidas'},
    { id: 14882, descricao: 'Destinação de Recursos Decorrentes da Pena de Prestação Pecuniária'},
    { id: 3396, descricao: 'Difamação'},
    { id: 11785, descricao: 'Diligências'},
    { id: 15036, descricao: 'Diligências'},
    { id: 12398, descricao: 'Divulgação de cena de estupro, sexo ou pornografia'},
    { id: 3413, descricao: 'Divulgação de segredo'},
    { id: 8884, descricao: 'Do Juiz'},
    { id: 9893, descricao: 'Do sistema nacional de armas'},
    { id: 8888, descricao: 'Dos Auxiliares da Justiça'},
    { id: 9518, descricao: 'Efeito Suspensivo / Impugnação / Embargos à Execução'},
    { id: 9047, descricao: 'Efeitos'},
    { id: 11082, descricao: 'Efeitos da Condenação'},
    { id: 11583, descricao: 'Eleições'},
    { id: 12984, descricao: 'Emenda a inicial'},
    { id: 14960, descricao: 'Encaminhamento ao Comando do Exército'},
    { id: 10013, descricao: 'Enriquecimento ilícito'},
    { id: 11797, descricao: 'Entrada de aparelho telefônico de comunicação móvel em estabelecimento prisional'},
    { id: 8986, descricao: 'Erro de Procedimento'},
    { id: 3425, descricao: 'Esbulho possessório'},
    { id: 11106, descricao: 'Estado de Necessidade'},
    { id: 5971, descricao: 'Estaduais'},
    { id: 9895, descricao: 'Estatuto da criança e do adolescente'},
    { id: 3431, descricao: 'Estelionato'},
    { id: 11146, descricao: 'Estelionato e outras fraudes'},
    { id: 11108, descricao: 'Estrito Cumprimento do Dever Legal'},
    { id: 3465, descricao: 'Estupro'},
    { id: 11417, descricao: 'Estupro de Vulnerável'},
    { id: 10902, descricao: 'Excesso de prazo para instrução / julgamento'},
    { id: 10683, descricao: 'Exceção de Pré-executividade'},
    { id: 11083, descricao: 'Excludentes'},
    { id: 11052, descricao: 'Execução Penal'},
    { id: 7942, descricao: 'Execução Penal e de Medidas Alternativas'},
    { id: 10908, descricao: 'Execução Penal Provisória - Cabimento'},
    { id: 10880, descricao: 'Execução Provisória'},
    { id: 3581, descricao: 'Exercício arbitrário das próprias razões'},
    { id: 3585, descricao: 'Exercício arbitrário ou abuso de poder'},
    { id: 11118, descricao: 'Exercício de comércio'},
    { id: 9180, descricao: 'Expropriação de Bens'},
    { id: 9414, descricao: 'Extinção da Execução'},
    { id: 11084, descricao: 'Extinção da punibilidade'},
    { id: 8942, descricao: 'Extinção do Processo Sem Resolução de Mérito'},
    { id: 3420, descricao: 'Extorção'},
    { id: 11060, descricao: 'Exílio local'},
    { id: 10668, descricao: 'Fac-símile'},
    { id: 3542, descricao: 'Falsa Identidade'},
    { id: 7945, descricao: 'Falsidade'},
    { id: 11313, descricao: 'Falsidade'},
    { id: 3533, descricao: 'Falsidade Ideológica'},
    { id: 9815, descricao: 'Falsidade ideológica (art. 299)'},
    { id: 3530, descricao: 'Falsificação do selo ou sinal público'},
    { id: 3579, descricao: 'Falso testemunho ou falsa perícia'},
    { id: 10952, descricao: 'Fato Atípico '},
    { id: 7947, descricao: 'Fatos Jurídicos'},
    { id: 11419, descricao: 'Favorecimento da prostituição ou outra forma de exploração sexual de vulnerável'},
    { id: 3583, descricao: 'Favorecimento Pessoal'},
    { id: 3584, descricao: 'Favorecimento Real'},
    { id: 12091, descricao: 'Feminicídio'},
    { id: 10015, descricao: 'Fiscalização'},
    { id: 8938, descricao: 'Formação, Suspensão e Extinção do Processo'},
    { id: 10679, descricao: 'Fracionamento'},
    { id: 3582, descricao: 'Fraude Processual'},
    { id: 9450, descricao: 'Fraude à Execução'},
    { id: 3452, descricao: 'Frustração de direitos assegurados por lei trabalhista'},
    { id: 3586, descricao: 'Fuga de pessoa presa ou submetida a medida de segurança'},
    { id: 11269, descricao: 'Fuga, evasão, arrebatamento e amotinamento de presos'},
    { id: 3416, descricao: 'Furto'},
    { id: 11147, descricao: 'Furto'},
    { id: 11226, descricao: 'Genocídio'},
    { id: 5556, descricao: 'Grave'},
    { id: 5557, descricao: 'Gravíssima'},
    { id: 10891, descricao: 'Habeas Corpus - Cabimento'},
    { id: 11227, descricao: 'Homicídio'},
    { id: 12130, descricao: 'Homicídio Agravado pela Prática de Extermínio de Seres Humanos'},
    { id: 3370, descricao: 'Homicídio simples'},
    { id: 10655, descricao: 'Honorários Advocatícios'},
    { id: 10656, descricao: 'Honorários Advocatícios em Execução Contra a Fazenda Pública'},
    { id: 9258, descricao: 'Honorários Periciais'},
    { id: 10531, descricao: 'ICMS / Incidência Sobre o Ativo Fixo'},
    { id: 10600, descricao: 'Impedimento'},
    { id: 10660, descricao: 'Impedimento'},
    { id: 10365, descricao: 'Impedimento / Detenção / Prisão'},
    { id: 12384, descricao: 'Importunação Sexual'},
    { id: 12397, descricao: 'Importunação sexual '},
    { id: 10011, descricao: 'Improbidade Administrativa'},
    { id: 8838, descricao: 'Imunidade de Jurisdição'},
    { id: 10909, descricao: 'Imunidade em razão de função, ofício ou profissão'},
    { id: 11092, descricao: 'Inabilitação para o exercício de Função Pública'},
    { id: 5869, descricao: 'Incitação ao crime'},
    { id: 11093, descricao: 'Incompatibilidade para o Oficialato'},
    { id: 3492, descricao: 'Incêndio'},
    { id: 11961, descricao: 'Incêndio culposo'},
    { id: 1723, descricao: 'Indenizaçao por Dano Moral'},
    { id: 9524, descricao: 'Indenização do Prejuízo'},
    { id: 8808, descricao: 'Indenização por Dano Material'},
    { id: 11094, descricao: 'Indignidade para o Oficialato'},
    { id: 10913, descricao: 'Indisponibilidade / Seqüestro de Bens'},
    { id: 11101, descricao: 'Indulto'},
    { id: 10022, descricao: 'Infração Administrativa'},
    { id: 3515, descricao: 'Infração de Medida Sanitária Preventiva'},
    { id: 3397, descricao: 'Injúria'},
    { id: 10009, descricao: 'Inquérito / Processo / Recurso Administrativo'},
    { id: 3596, descricao: 'Inserção de dados falsos em sistema de informações'},
    { id: 11270, descricao: 'Insubordinação'},
    { id: 11061, descricao: 'Interdição de estabecimento  ou associação'},
    { id: 10735, descricao: 'Interesse Processual'},
    { id: 7795, descricao: 'Internação'},
    { id: 15042, descricao: 'Interrogatório'},
    { id: 3504, descricao: 'Interrupção /perturbação de serviços telegráficos/telefônicos'},
    { id: 8859, descricao: 'Intervenção de Terceiros '},
    { id: 11782, descricao: 'Intimação'},
    { id: 15035, descricao: 'Intimação'},
    { id: 10939, descricao: 'Intimação / Notificação'},
    { id: 15128, descricao: 'Intolerância e/ou Injúria Racial, de Cor e/ou Etnia'},
    { id: 11978, descricao: 'Invasão de Dispositivo Informático'},
    { id: 10604, descricao: 'Investigação Penal'},
    { id: 11067, descricao: 'Irregularidade na composição do Conselho'},
    { id: 12352, descricao: 'Jogo do bicho'},
    { id: 12350, descricao: 'Jogos de azar'},
    { id: 4291, descricao: 'Jurisdição e Competência'},
    { id: 8828, descricao: 'Jurisdição e Competência'},
    { id: 11053, descricao: 'Jurisdição e Competência'},
    { id: 10684, descricao: 'Juros'},
    { id: 10982, descricao: 'Lavagem ou Ocultação de Bens, Direitos ou Valores Oriundos de Corrupção'},
    { id: 13004, descricao: 'Legitimidade - Autoridade Coatora'},
    { id: 10736, descricao: 'Legitimidade para a Causa'},
    { id: 10863, descricao: 'Legitimidade para propositura de Ação Civil Pública'},
    { id: 11111, descricao: 'Legítima Defesa'},
    { id: 3385, descricao: 'Lesão corporal'},
    { id: 11228, descricao: 'Lesão Corporal e Rixa'},
    { id: 9160, descricao: 'Levantamento de Valor'},
    { id: 3386, descricao: 'Leve'},
    { id: 7928, descricao: 'Liberdade Provisória'},
    { id: 10366, descricao: 'Licenciamento / Exclusão'},
    { id: 9196, descricao: 'Liminar '},
    { id: 9148, descricao: 'Liquidação / Cumprimento / Execução'},
    { id: 8865, descricao: 'Litigância de Má-Fé'},
    { id: 8866, descricao: 'Litisconsórcio e Assistência'},
    { id: 10636, descricao: 'Livramento condicional'},
    { id: 11085, descricao: 'Livramento Condicional'},
    { id: 10187, descricao: 'Magistratura'},
    { id: 12940, descricao: 'Mandado de segurança'},
    { id: 10508, descricao: 'Maus tratos'},
    { id: 14782, descricao: 'Maus tratos'},
    { id: 9192, descricao: 'Medida Cautelar'},
    { id: 10912, descricao: 'Medidas Assecuratórias'},
    { id: 7793, descricao: 'Medidas de Segurança'},
    { id: 11054, descricao: 'Menagem'},
    { id: 10324, descricao: 'Militar'},
    { id: 8875, descricao: 'Ministério Público'},
    { id: 8941, descricao: 'Modificação ou Alteração do Pedido'},
    { id: 11102, descricao: 'Morte do Agente'},
    { id: 11271, descricao: 'Motim e Revolta'},
    { id: 10686, descricao: 'Multa Cominatória / Astreintes'},
    { id: 9166, descricao: 'Multa de 10%'},
    { id: 10023, descricao: 'Multas e demais Sanções'},
    { id: 4264, descricao: 'Nulidade'},
    { id: 8919, descricao: 'Nulidade'},
    { id: 11066, descricao: 'Nulidade'},
    { id: 9178, descricao: 'Nulidade / Inexigibilidade do Título'},
    { id: 15033, descricao: 'Objetos de Cartas Precatórias Criminais'},
    { id: 11781, descricao: 'Objetos de cartas precatórias/de ordem'},
    { id: 10671, descricao: 'Obrigação de Fazer / Não Fazer'},
    { id: 11784, descricao: 'Oitiva'},
    { id: 15041, descricao: 'Oitiva'},
    { id: 12355, descricao: 'Omissão de comunicação de crime'},
    { id: 3392, descricao: 'Omissão de socorro'},
    { id: 10869, descricao: 'Parcela Incontroversa'},
    { id: 11080, descricao: 'Parte Geral '},
    { id: 8842, descricao: 'Partes e Procuradores'},
    { id: 11314, descricao: 'Peculato'},
    { id: 7791, descricao: 'Pena Privativa de Liberdade'},
    { id: 11086, descricao: 'Penas Acessórias'},
    { id: 11057, descricao: 'Penas restritivas de direitos'},
    { id: 13019, descricao: 'Penhora de Salário / Proventos'},
    { id: 11096, descricao: 'Perda da Graduação das Praças '},
    { id: 11097, descricao: 'Perda do Posto e da Patente'},
    { id: 11112, descricao: 'Perda em favor da Fazenda Pública'},
    { id: 3388, descricao: 'Periclitação da Vida e da Saúde e Rixa'},
    { id: 11229, descricao: 'Periclitação da Vida ou da Saúde'},
    { id: 3390, descricao: 'Perigo para a vida ou saúde de outrem'},
    { id: 14684, descricao: 'Perseguição'},
    { id: 12354, descricao: 'Perturbação da tranquilidade'},
    { id: 5754, descricao: 'Pessoas naturais'},
    { id: 5885, descricao: 'Posse de Drogas para Consumo Pessoal'},
    { id: 9628, descricao: 'Praticados por Funcionários Públicos Contra a Administração em Geral'},
    { id: 9917, descricao: 'Praticados por Particular Contra a Administração em Geral'},
    { id: 8928, descricao: 'Prazo'},
    { id: 13023, descricao: 'Prazo decadencial'},
    { id: 10672, descricao: 'Precatório'},
    { id: 9050, descricao: 'Preparo / Deserção'},
    { id: 11103, descricao: 'Prescrição'},
    { id: 5632, descricao: 'Prescrição e Decadência'},
    { id: 3557, descricao: 'Prevaricação'},
    { id: 9847, descricao: 'Previstos na Legislação Extravagante'},
    { id: 11090, descricao: 'Princípio da Insignificância'},
    { id: 10573, descricao: 'Prisão Civil'},
    { id: 10640, descricao: 'Prisão Decorrente de Sentença Condenatória'},
    { id: 15043, descricao: 'Prisão domiciliar'},
    { id: 10904, descricao: 'Prisão Domiciliar / Especial'},
    { id: 7929, descricao: 'Prisão em flagrante'},
    { id: 4355, descricao: 'Prisão Preventiva'},
    { id: 15038, descricao: 'Prisão Preventiva'},
    { id: 15039, descricao: 'Prisão Temporária'},
    { id: 5558, descricao: 'Privilegiada'},
    { id: 10363, descricao: 'Processo Administrativo Disciplinar / Sindicância'},
    { id: 10190, descricao: 'Processo Disciplinar / Sindicância'},
    { id: 8960, descricao: 'Processo e Procedimento'},
    { id: 8868, descricao: 'Procuração / Mandato'},
    { id: 14238, descricao: 'Produção Antecipada de Provas'},
    { id: 10635, descricao: 'Progressão de Regime'},
    { id: 11062, descricao: 'Proibição de frequentar determinados locais'},
    { id: 10192, descricao: 'Promoção'},
    { id: 12334, descricao: 'Promoção, constituição, financiamento ou integração de Organização Criminosa'},
    { id: 11652, descricao: 'Propaganda Política - Propaganda Eleitoral'},
    { id: 11683, descricao: 'Propaganda Política - Propaganda Eleitoral - Truncagem, Montagem, Utilização de Gravação Externa, Computação Gráfica, Desenho Animado ou Efeito Especi'},
    { id: 10669, descricao: 'Protocolo Integrado / Descentralizado'},
    { id: 10926, descricao: 'Prova Ilícita'},
    { id: 13032, descricao: 'Prova Pré-constituída'},
    { id: 8990, descricao: 'Provas'},
    { id: 10925, descricao: 'Provas'},
    { id: 3521, descricao: 'Quadrilha ou bando'},
    { id: 14124, descricao: 'Quebra de Sigilo Telemático'},
    { id: 10607, descricao: 'Quebra do Sigilo Bancário'},
    { id: 10608, descricao: 'Quebra do Sigilo Fiscal'},
    { id: 10609, descricao: 'Quebra do Sigilo Telefônico'},
    { id: 10691, descricao: 'Questão Prejudicial'},
    { id: 14880, descricao: 'Questões Incidentes'},
    { id: 10675, descricao: 'Quinto Constitucional'},
    { id: 11104, descricao: 'Reabilitação'},
    { id: 4370, descricao: 'Recebimento'},
    { id: 3435, descricao: 'Receptação'},
    { id: 11148, descricao: 'Receptação'},
    { id: 4305, descricao: 'Recurso'},
    { id: 9045, descricao: 'Recurso'},
    { id: 12356, descricao: 'Recusa de dados sobre a própria identificação ou qualificação'},
    { id: 3404, descricao: 'Redução a condição análoga à de escravo'},
    { id: 10325, descricao: 'Regime'},
    { id: 14703, descricao: 'Registro Não Autorizado da Intimidade Sexual'},
    { id: 10906, descricao: 'Regressão de Regime'},
    { id: 10666, descricao: 'Regularidade Formal'},
    { id: 10328, descricao: 'Reintegração'},
    { id: 13035, descricao: 'Reiteração'},
    { id: 4371, descricao: 'Rejeição'},
    { id: 9189, descricao: 'Remição'},
    { id: 10637, descricao: 'Remição'},
    { id: 10193, descricao: 'Remoção'},
    { id: 10188, descricao: 'Remuneração'},
    { id: 11113, descricao: 'Reparação do Dano'},
    { id: 11064, descricao: 'Representação do Corregedor'},
    { id: 8873, descricao: 'Representação em Juízo'},
    { id: 11065, descricao: 'Requerimento da Parte'},
    { id: 10673, descricao: 'Requisição de Pequeno Valor - RPV'},
    { id: 10734, descricao: 'Reserva de Plenário'},
    { id: 11272, descricao: 'Resistência'},
    { id: 2567, descricao: 'Responsabilidade Civil do Empregador'},
    { id: 11105, descricao: 'Ressarcimento do Dano'},
    { id: 14957, descricao: 'Restituição de Coisas Apreendidas'},
    { id: 9024, descricao: 'Revelia '},
    { id: 3419, descricao: 'Roubo'},
    { id: 11149, descricao: 'Roubo e Extorsão'},
    { id: 5854, descricao: 'Rufianismo'},
    { id: 3387, descricao: 'Seguida de morte'},
    { id: 10678, descricao: 'Sequestro de Verbas Públicas'},
    { id: 3403, descricao: 'Seqüestro e cárcere privado'},
    { id: 12544, descricao: 'Simples'},
    { id: 12348, descricao: 'Simulação de Qualidade de Funcionário'},
    { id: 10738, descricao: 'Sobrestamento'},
    { id: 9494, descricao: 'Substituição da Parte'},
    { id: 11115, descricao: 'Substituição da Pena'},
    { id: 8867, descricao: 'Substituição Processual'},
    { id: 9484, descricao: 'Sucessão'},
    { id: 8874, descricao: 'Sucumbência '},
    { id: 10601, descricao: 'Suspeição'},
    { id: 10659, descricao: 'Suspeição'},
    { id: 4271, descricao: 'Suspensão'},
    { id: 10367, descricao: 'Suspensão'},
    { id: 11087, descricao: 'Suspensão Condicional da Pena'},
    { id: 11063, descricao: 'Suspensão do exercício do posto, graduação, cargo ou função'},
    { id: 8939, descricao: 'Suspensão do Processo'},
    { id: 11098, descricao: 'Suspensão do pátrio poder, tutela ou curatela'},
    { id: 11099, descricao: 'Suspensão dos direitos políticos'},
    { id: 5956, descricao: 'Taxas'},
    { id: 9060, descricao: 'Tempestividade'},
    { id: 11088, descricao: 'Tipicidade'},
    { id: 4272, descricao: 'Trancamento'},
    { id: 10610, descricao: 'Trancamento'},
    { id: 10907, descricao: 'Transferência de Preso'},
    { id: 7794, descricao: 'Tratamento Ambulatorial'},
    { id: 3608, descricao: 'Tráfico de drogas e Condutas Afins'},
    { id: 9859, descricao: 'Tráfico de Drogas e Condutas Afins'},
    { id: 3567, descricao: 'Tráfico de Influência'},
    { id: 3462, descricao: 'Ultraje / Impedimento ou Perturbação de Culto Religioso'},
    { id: 11230, descricao: 'Ultraje Público ao Pudor'},
    { id: 3494, descricao: 'Uso de gás tóxico ou asfixiante'},
    { id: 12349, descricao: 'Uso ilegítimo de uniforme ou distintivo'},
    { id: 11150, descricao: 'Usura'},
    { id: 11151, descricao: 'Usurpação'},
    { id: 3565, descricao: 'Usurpação de função pública'},
    { id: 9918, descricao: 'Usurpação de função pública (art. 328)'},
    { id: 11273, descricao: 'Usurpação e excesso ou abuso de autoridade'},
    { id: 8934, descricao: 'Valor da Causa'},
    { id: 9149, descricao: 'Valor da Execução / Cálculo / Atualização'},
    { id: 12345, descricao: 'Vias de fato'},
    { id: 10014, descricao: 'Violação aos Princípios Administrativos'},
    { id: 3406, descricao: 'Violação de domicílio'},
    { id: 3414, descricao: 'Violação do segredo profissional'},
    { id: 3563, descricao: 'Violação do sigilo funcional'},
    { id: 3560, descricao: 'Violência arbitrária (art. 322)'},
    { id: 9840, descricao: 'Violência arbitrária (art. 322)'},
    { id: 11274, descricao: 'Violência contra superior ou militar de serviço'},
    { id: 14942, descricao: 'Violência Psicológica contra a Mulher'},
    { id: 10890, descricao: 'Vício Formal do Julgamento'},
    { id: 9026, descricao: 'Vícios Formais da Sentença'},
    { id: 8883, descricao: 'Órgãos Judiciários e Auxiliares da Justiça'},
]);

export default AssuntosEnum;
