// src/enums/AssuntosEnum.js

const AssuntosEnum = Object.freeze([
	{ id: 1855, descricao: 'Indenizaçao por Dano Moral,' },
    { id: 3369, descricao: 'Crimes contra a vida,' },
    { id: 3370, descricao: 'Homicídio simples,' },
    { id: 3385, descricao: 'Lesão corporal,' },
    { id: 3386, descricao: 'Leve,' },
    { id: 3390, descricao: 'Perigo para a vida ou saúde de outrem,' },
    { id: 3392, descricao: 'Omissão de socorro,' },
    { id: 3395, descricao: 'Calúnia,' },
    { id: 3396, descricao: 'Difamação,' },
    { id: 3401, descricao: 'Constrangimento Ilegal,' },
    { id: 3402, descricao: 'Ameaça,' },
    { id: 3416, descricao: 'Furto,' },
    { id: 3426, descricao: 'Dano (Art. 163),' },
    { id: 3431, descricao: 'Estelionato,' },
    { id: 3465, descricao: 'Estupro,' },
    { id: 3494, descricao: 'Uso de gás tóxico ou asfixiante,' },
    { id: 3521, descricao: 'Quadrilha ou bando,' },
    { id: 3533, descricao: 'Falsidade Ideológica,' },
    { id: 3542, descricao: 'Falsa Identidade,' },
    { id: 3547, descricao: 'Crimes Praticados por Funcionários Públicos Contra a Administração em Geral,' },
    { id: 3555, descricao: 'Corrupção Passiva,' },
    { id: 3557, descricao: 'Prevaricação,' },
    { id: 3559, descricao: 'Advocacia administrativa,' },
    { id: 3560, descricao: 'Violência arbitrária (art. 322),' },
    { id: 3563, descricao: 'Violação do sigilo funcional,' },
    { id: 3576, descricao: 'Denunciação caluniosa,' },
    { id: 3579, descricao: 'Falso testemunho ou falsa perícia,' },
    { id: 3580, descricao: 'Coação no curso do processo,' },
    { id: 3582, descricao: 'Fraude Processual,' },
    { id: 3585, descricao: 'Exercício arbitrário ou abuso de poder,' },
    { id: 3603, descricao: 'Crimes Previstos na Legislação Extravagante,' },
    { id: 3605, descricao: 'Crimes contra a Economia Popular,' },
    { id: 3606, descricao: 'Crimes de Abuso de Autoridade,' },
    { id: 3608, descricao: 'Tráfico de drogas e Condutas Afins,' },
    { id: 3620, descricao: 'Crime contra a flora,' },
    { id: 3631, descricao: 'Crimes de Tortura,' },
    { id: 3632, descricao: 'Crimes de Trânsito,' },
    { id: 3633, descricao: 'Crimes do Sistema Nacional de Armas,' },
    { id: 3637, descricao: 'Crimes Previstos no Estatuto da criança e do adolescente,' },
    { id: 4263, descricao: 'Ação Penal,' },
    { id: 4264, descricao: 'Nulidade,' },
    { id: 4271, descricao: 'Suspensão,' },
    { id: 4272, descricao: 'Trancamento,' },
    { id: 4305, descricao: 'Recurso,' },
    { id: 4355, descricao: 'Prisão Preventiva,' },
    { id: 4368, descricao: 'Denúncia/Queixa,' },
    { id: 4370, descricao: 'Recebimento,' },
    { id: 4371, descricao: 'Rejeição,' },
    { id: 4703, descricao: 'Defeito, nulidade ou anulação,' },
    { id: 5555, descricao: 'Crime Tentado,' },
    { id: 5556, descricao: 'Grave,' },
    { id: 5557, descricao: 'Gravíssima,' },
    { id: 5632, descricao: 'Prescrição e Decadência,' },
    { id: 5754, descricao: 'Pessoas naturais,' },
    { id: 5851, descricao: 'Assédio Sexual,' },
    { id: 5854, descricao: 'Rufianismo,' },
    { id: 5897, descricao: 'Associação para a Produção e Tráfico e Condutas Afins,' },
    { id: 5899, descricao: 'Colaboração com Grupo, Organização ou Associação Destinados à Produção ou Tráfico de Drogas,' },
    { id: 7791, descricao: 'Pena Privativa de Liberdade,' },
    { id: 7928, descricao: 'Liberdade Provisória,' },
    { id: 7940, descricao: 'Deserção,' },
    { id: 7941, descricao: 'Denegação,' },
    { id: 7945, descricao: 'Falsidade,' },
    { id: 8843, descricao: 'Assistência Judiciária Gratuita,' },
    { id: 8919, descricao: 'Nulidade,' },
    { id: 8961, descricao: 'Antecipação de Tutela / Tutela Específica,' },
    { id: 8990, descricao: 'Provas,' },
    { id: 9026, descricao: 'Vícios Formais da Sentença,' },
    { id: 9045, descricao: 'Recurso,' },
    { id: 9047, descricao: 'Efeitos,' },
    { id: 9148, descricao: 'Liquidação / Cumprimento / Execução,' },
    { id: 9196, descricao: 'Liminar ,' },
    { id: 9517, descricao: 'Causas Supervenientes à Sentença,' },
    { id: 9518, descricao: 'Efeito Suspensivo / Impugnação / Embargos à Execução,' },
    { id: 9660, descricao: 'Constrangimento ilegal,' },
    { id: 9661, descricao: 'Ameaça,' },
    { id: 9840, descricao: 'Violência arbitrária (art. 322),' },
    { id: 9859, descricao: 'Tráfico de Drogas e Condutas Afins,' },
    { id: 9893, descricao: 'Do sistema nacional de armas,' },
    { id: 9895, descricao: 'Estatuto da criança e do adolescente,' },
    { id: 9997, descricao: 'Atos Administrativos,' },
    { id: 10009, descricao: 'Inquérito / Processo / Recurso Administrativo,' },
    { id: 10011, descricao: 'Improbidade Administrativa,' },
    { id: 10014, descricao: 'Violação aos Princípios Administrativos,' },
    { id: 10022, descricao: 'Infração Administrativa,' },
    { id: 10023, descricao: 'Multas e demais Sanções,' },
    { id: 10186, descricao: 'Agentes Políticos,' },
    { id: 10190, descricao: 'Processo Disciplinar / Sindicância,' },
    { id: 10192, descricao: 'Promoção,' },
    { id: 10324, descricao: 'Militar,' },
    { id: 10325, descricao: 'Regime,' },
    { id: 10328, descricao: 'Reintegração,' },
    { id: 10363, descricao: 'Processo Administrativo Disciplinar / Sindicância,' },
    { id: 10364, descricao: 'Advertência / Repreensão,' },
    { id: 10365, descricao: 'Impedimento / Detenção / Prisão,' },
    { id: 10366, descricao: 'Licenciamento / Exclusão,' },
    { id: 10367, descricao: 'Suspensão,' },
    { id: 10370, descricao: 'Concurso Público / Edital,' },
    { id: 10379, descricao: 'Anulação e Correção de Provas / Questões,' },
    { id: 10381, descricao: 'Classificação e/ou Preterição,' },
    { id: 10382, descricao: 'Anulação,' },
    { id: 10600, descricao: 'Impedimento,' },
    { id: 10601, descricao: 'Suspeição,' },
    { id: 10604, descricao: 'Investigação Penal,' },
    { id: 10606, descricao: 'Cerceamento de Defesa,' },
    { id: 10607, descricao: 'Quebra do Sigilo Bancário,' },
    { id: 10608, descricao: 'Quebra do Sigilo Fiscal,' },
    { id: 10609, descricao: 'Quebra do Sigilo Telefônico,' },
    { id: 10610, descricao: 'Trancamento,' },
    { id: 10631, descricao: 'Desaforamento,' },
    { id: 10635, descricao: 'Progressão de Regime,' },
    { id: 10637, descricao: 'Remição,' },
    { id: 10655, descricao: 'Honorários Advocatícios,' },
    { id: 10656, descricao: 'Honorários Advocatícios em Execução Contra a Fazenda Pública,' },
    { id: 10659, descricao: 'Suspeição,' },
    { id: 10673, descricao: 'Requisição de Pequeno Valor - RPV,' },
    { id: 10678, descricao: 'Sequestro de Verbas Públicas,' },
    { id: 10691, descricao: 'Questão Prejudicial,' },
    { id: 10865, descricao: 'Cerceamento de Defesa,' },
    { id: 10867, descricao: 'Ausência de Fundamentação,' },
    { id: 10869, descricao: 'Parcela Incontroversa,' },
    { id: 10891, descricao: 'Habeas Corpus - Cabimento,' },
    { id: 10894, descricao: 'Abuso de Poder,' },
    { id: 10898, descricao: 'Competência da Justiça Federal,' },
    { id: 10899, descricao: 'Competência da Justiça Estadual,' },
    { id: 10902, descricao: 'Excesso de prazo para instrução / julgamento,' },
    { id: 10904, descricao: 'Prisão Domiciliar / Especial,' },
    { id: 10908, descricao: 'Execução Penal Provisória - Cabimento,' },
    { id: 10912, descricao: 'Medidas Assecuratórias,' },
    { id: 10913, descricao: 'Indisponibilidade / Seqüestro de Bens,' },
    { id: 10914, descricao: 'Busca e Apreensão de Bens,' },
    { id: 10925, descricao: 'Provas,' },
    { id: 10926, descricao: 'Prova Ilícita,' },
    { id: 10940, descricao: 'Depoimento,' },
    { id: 10950, descricao: 'Crime / Contravenção contra Criança / Adolescente,' },
    { id: 10952, descricao: 'Fato Atípico ,' },
    { id: 10982, descricao: 'Lavagem ou Ocultação de Bens, Direitos ou Valores Oriundos de Corrupção,' },
    { id: 10986, descricao: 'Crime contra a administração ambiental,' },
    { id: 11050, descricao: 'Ação Penal Militar,' },
    { id: 11051, descricao: 'Correição Parcial,' },
    { id: 11052, descricao: 'Execução Penal,' },
    { id: 11053, descricao: 'Jurisdição e Competência,' },
    { id: 11056, descricao: 'Competência da Justiça Militar Estadual,' },
    { id: 11063, descricao: 'Suspensão do exercício do posto, graduação, cargo ou função,' },
    { id: 11064, descricao: 'Representação do Corregedor,' },
    { id: 11065, descricao: 'Requerimento da Parte,' },
    { id: 11066, descricao: 'Nulidade,' },
    { id: 11067, descricao: 'Irregularidade na composição do Conselho,' },
    { id: 11069, descricao: 'Crime Culposo,' },
    { id: 11071, descricao: 'Crime Tentado,' },
    { id: 11073, descricao: 'Crimes contra a Administração Militar,' },
    { id: 11075, descricao: 'Crimes contra a Pessoa,' },
    { id: 11078, descricao: 'Crimes contra o Patrimônio,' },
    { id: 11079, descricao: 'Crimes contra o Serviço Militar e o Dever Militar,' },
    { id: 11084, descricao: 'Extinção da punibilidade,' },
    { id: 11087, descricao: 'Suspensão Condicional da Pena,' },
    { id: 11093, descricao: 'Incompatibilidade para o Oficialato,' },
    { id: 11094, descricao: 'Indignidade para o Oficialato,' },
    { id: 11096, descricao: 'Perda da Graduação das Praças ,' },
    { id: 11097, descricao: 'Perda do Posto e da Patente,' },
    { id: 11101, descricao: 'Indulto,' },
    { id: 11103, descricao: 'Prescrição,' },
    { id: 11104, descricao: 'Reabilitação,' },
    { id: 11112, descricao: 'Perda em favor da Fazenda Pública,' },
    { id: 11115, descricao: 'Substituição da Pena,' },
    { id: 11116, descricao: 'Abandono de posto e de outros crimes em serviço,' },
    { id: 11117, descricao: 'Deserção,' },
    { id: 11125, descricao: 'Exercício de comércio por oficial,' },
    { id: 11127, descricao: 'Deserção,' },
    { id: 11128, descricao: 'Deserção - casos assimilados,' },
    { id: 11130, descricao: 'Deserção por evasão ou fuga,' },
    { id: 11131, descricao: 'Deserção privilegiada,' },
    { id: 11132, descricao: 'Deserção qualificada,' },
    { id: 11135, descricao: 'Abandono de posto,' },
    { id: 11136, descricao: 'Descumprimento de missão,' },
    { id: 11137, descricao: 'Dormir em serviço,' },
    { id: 11138, descricao: 'Embriaguez em serviço,' },
    { id: 11146, descricao: 'Estelionato e outras fraudes,' },
    { id: 11147, descricao: 'Furto,' },
    { id: 11152, descricao: 'Alteração de Limites ,' },
    { id: 11155, descricao: 'Chantagem,' },
    { id: 11156, descricao: 'Extorsão ,' },
    { id: 11158, descricao: 'Extorsão mediante sequestro,' },
    { id: 11160, descricao: 'Roubo,' },
    { id: 11163, descricao: 'Furto ,' },
    { id: 11164, descricao: 'Furto de uso,' },
    { id: 11165, descricao: 'Furto qualificado,' },
    { id: 11167, descricao: 'Estelionato,' },
    { id: 11171, descricao: 'Dano material ou aparelhamento de guerra,' },
    { id: 11172, descricao: 'Dano qualificado,' },
    { id: 11173, descricao: 'Dano simples,' },
    { id: 11177, descricao: 'Apropriação indébita,' },
    { id: 11197, descricao: 'Atentado contra viatura ou outro meio de transporte,' },
    { id: 11198, descricao: 'Interrupção ou perturbação de serviço ou meio de comunicação,' },
    { id: 11207, descricao: 'Tráfico, posse ou uso de entorpecente ou substância de efeito similar,' },
    { id: 11223, descricao: 'Crimes contra a Honra,' },
    { id: 11227, descricao: 'Homicídio,' },
    { id: 11233, descricao: 'Abandono de pessoa,' },
    { id: 11235, descricao: 'Maus tratos,' },
    { id: 11237, descricao: 'Lesão grave,' },
    { id: 11238, descricao: 'Lesão leve,' },
    { id: 11239, descricao: 'Lesão levíssima,' },
    { id: 11241, descricao: 'Lesão seguida de morte,' },
    { id: 11243, descricao: 'Homicídio,' },
    { id: 11244, descricao: 'Homicidio qualificado,' },
    { id: 11249, descricao: 'Atentado violento ao pudor,' },
    { id: 11250, descricao: 'Corrupção de menores,' },
    { id: 11251, descricao: 'Estupro,' },
    { id: 11252, descricao: 'Pederastia ou outro ato de libidinagem,' },
    { id: 11253, descricao: 'Ameaça,' },
    { id: 11254, descricao: 'Constragimento ilegal,' },
    { id: 11257, descricao: 'Sequestro ou cárcere privado,' },
    { id: 11259, descricao: 'Violação de domicílio,' },
    { id: 11260, descricao: 'Violação de recato,' },
    { id: 11262, descricao: 'Calúnia,' },
    { id: 11263, descricao: 'Difamação,' },
    { id: 11264, descricao: 'Injúria,' },
    { id: 11265, descricao: 'Injuria real,' },
    { id: 11273, descricao: 'Usurpação e excesso ou abuso de autoridade,' },
    { id: 11275, descricao: 'Violência contra militar de serviço,' },
    { id: 11276, descricao: 'Violência contra superior,' },
    { id: 11286, descricao: 'Violência contra inferior,' },
    { id: 11287, descricao: 'Resistência mediante ameaça ou violência,' },
    { id: 11291, descricao: 'Organização de grupo para prática de violência,' },
    { id: 11293, descricao: 'Oposição a ordem de sentinela,' },
    { id: 11294, descricao: 'Publicação ou crítica indevida,' },
    { id: 11295, descricao: 'Recusa a obediência,' },
    { id: 11296, descricao: 'Reunião ilícita,' },
    { id: 11299, descricao: 'Evasão de preso ou internado,' },
    { id: 11300, descricao: 'Fuga de preso ou internado,' },
    { id: 11303, descricao: 'Incitamento,' },
    { id: 11304, descricao: 'Despojamento desprezível,' },
    { id: 11307, descricao: 'Desrespeito a superior ,' },
    { id: 11308, descricao: 'Concussão, Excesso de Exação e Desvio,' },
    { id: 11309, descricao: 'Corrupção,' },
    { id: 11315, descricao: 'Peculato,' },
    { id: 11316, descricao: 'Peculato mediante aproveitamento ou erro de outrem,' },
    { id: 11317, descricao: 'Peculato-furto,' },
    { id: 11320, descricao: 'Falsa identidade,' },
    { id: 11321, descricao: 'Falsidade ideológica,' },
    { id: 11322, descricao: 'Falsificação de documento,' },
    { id: 11323, descricao: 'Supressão de documento,' },
    { id: 11324, descricao: 'Uso de documento falso,' },
    { id: 11327, descricao: 'Desacato a militar,' },
    { id: 11328, descricao: 'Desacato a superior,' },
    { id: 11329, descricao: 'Desobediência,' },
    { id: 11336, descricao: 'Abandono de cargo,' },
    { id: 11337, descricao: 'Abuso de confiança ou boa fé,' },
    { id: 11339, descricao: 'Condescendência criminosa,' },
    { id: 11341, descricao: 'Extravio, sonegação ou inutilização de livro ou documento,' },
    { id: 11342, descricao: 'Inobservancia de lei, regulamento ou instrução,' },
    { id: 11345, descricao: 'Patrocínio indébito,' },
    { id: 11346, descricao: 'Prevaricação,' },
    { id: 11347, descricao: 'Violação de sigilo de proposta de concorrência,' },
    { id: 11348, descricao: 'Violação de sigilo funcional,' },
    { id: 11349, descricao: 'Violação do dever funcional com o fim de lucro,' },
    { id: 11350, descricao: 'Violação ou divulgação indevida de correspondência ou comunicação,' },
    { id: 11351, descricao: 'Violência arbitrária,' },
    { id: 11352, descricao: 'Corrupção ativa,' },
    { id: 11353, descricao: 'Corrupção passiva,' },
    { id: 11355, descricao: 'Concussão,' },
    { id: 11359, descricao: 'Coação,' },
    { id: 11360, descricao: 'Comunicação falsa de crime,' },
    { id: 11361, descricao: 'Corrupção ativa de testemunha, perito ou intérprete,' },
    { id: 11362, descricao: 'Denunciação caluniosa,' },
    { id: 11363, descricao: 'Desacato,' },
    { id: 11364, descricao: 'Desobediência a decisão judicial,' },
    { id: 11365, descricao: 'Desobediência a decisão sobre perda ou suspensão de atividade ou direito,' },
    { id: 11367, descricao: 'Falso testemunho ou falsa perícia,' },
    { id: 11369, descricao: 'Favorecimento real,' },
    { id: 11370, descricao: 'Inutilização,sonegação ou descaminho de material probante,' },
    { id: 11417, descricao: 'Estupro de Vulnerável,' },
    { id: 11797, descricao: 'Entrada de aparelho telefônico de comunicação móvel em estabelecimento prisional,' },
    { id: 12091, descricao: 'Feminicídio,' },
    { id: 12333, descricao: 'Crimes previstos na Lei da Organização Criminosa,' },
    { id: 12334, descricao: 'Promoção, constituição, financiamento ou integração de Organização Criminosa,' },
    { id: 12345, descricao: 'Vias de fato,' },
    { id: 12350, descricao: 'Jogos de azar,' },
    { id: 12352, descricao: 'Jogo do bicho,' },
    { id: 12354, descricao: 'Perturbação da tranquilidade,' },
    { id: 12397, descricao: 'Importunação sexual ,' },
    { id: 12544, descricao: 'Simples,' },
    { id: 12612, descricao: 'COVID-19,' },
    { id: 13004, descricao: 'Legitimidade - Autoridade Coatora,' },
    { id: 13035, descricao: 'Reiteração,' },
    { id: 14124, descricao: 'Quebra de Sigilo Telemático,' },
    { id: 14238, descricao: 'Produção Antecipada de Provas,' },
    { id: 14684, descricao: 'Perseguição,' },
    { id: 14685, descricao: 'Associação Criminosa,' },
    { id: 14782, descricao: 'Maus tratos,' },
    { id: 14942, descricao: 'Violência Psicológica contra a Mulher,' },
    { id: 14957, descricao: 'Restituição de Coisas Apreendidas,' },
    { id: 15038, descricao: 'Prisão Preventiva,' },
    { id: 15128, descricao: 'Intolerância e/ou Injúria Racial, de Cor e/ou Etnia,' },
    { id: 15397, descricao: 'Crimes de Abuso de Autoridade (Lei 13.869/2019),' },
]);

export default AssuntosEnum;
