// src/enums/ClassesEnum.js

const ClassesEnum = Object.freeze([
    { id: 47, descricao: 'Ação rescisória' },
    { id: 413, descricao: 'Agravo de Execução Penal (Câmara)' },
    { id: 202, descricao: 'Agravo de Instrumento' },
    { id: 198, descricao: 'Apelação cível' },
    { id: 417, descricao: 'Apelação Criminal' },
    { id: 418, descricao: 'Carta Testemunhável' },
    { id: 325, descricao: 'Conflito de Jurisdição (Pleno)' },
    { id: 11034, descricao: 'Conselho de Justificação (Pleno)' },
    { id: 419, descricao: 'Correição Parcial (Câmara)' },
    { id: 11042, descricao: 'Correição Parcial (Pleno)' },
    { id: 11038, descricao: 'Embargos em Ação Penal Militar (Pleno)' },
    { id: 421, descricao: 'Embargos Infringentes e de Nulidade (Pleno)' },
    { id: 323, descricao: 'Exceção de Impedimento (Câmara)' },
    { id: 318, descricao: 'Exceção de Suspeição (Câmara)' },
    { id: 3181, descricao: 'Exceção de Suspeição (Pleno)' },
    { id: 307, descricao: 'Habeas Corpus (Competência: Câmara)' },
    { id: 3071, descricao: 'Habeas Corpus (Competência: Pleno)' },
    { id: 12087, descricao: 'Incidente de Assunção de Competência' },
    { id: 12085, descricao: 'Incidente de Resolução de Demandas Repetitivas' },
    { id: 1710, descricao: 'Mandado de Segurança (Câmara)' },
    { id: 1201, descricao: 'Mandado de Segurança Cível (Pleno)' },
    { id: 241, descricao: 'Petição cível (Câmara)' },
    { id: 2411, descricao: 'Petição Cível (Pleno)' },
    { id: 1727, descricao: 'Petição Criminal (Câmara)' },
    { id: 426, descricao: 'Recurso em Sentido Estrito (Câmara)' },
    { id: 11040, descricao: 'Recurso Inominado Militar' },
    { id: 11035, descricao: 'Representação p/ Declaração de Indignidade/Incompatibilidade (Pleno)' },
    { id: 11036, descricao: 'Representação p/ Perda da Graduação (Pleno)' },
    { id: 428, descricao: 'Revisão Criminal (Pleno)' },
    { id: 12394, descricao: 'Revisão Criminal (Pleno)' },
]);

export default ClassesEnum;
