// src/enums/TribunaisEnum.js

const TribunaisEnum = Object.freeze([
    { id:14141, descricao:  'JME/MG - 1ª Auditoria', tribunal: 31, indeterminate: false },
    { id:14142, descricao:  'JME/MG - 2ª Auditoria', tribunal: 31, indeterminate: false },
    { id:14143, descricao:  'JME/MG - 3ª Auditoria', tribunal: 31, indeterminate: false },
    { id:81647, descricao:  'JME/MG - 4ª Auditoria', tribunal: 31, indeterminate: false },
    { id:81648, descricao:  'JME/MG - 5ª Auditoria', tribunal: 31, indeterminate: false },
    { id:13231, descricao:  'JME/RS - 1ª Auditoria', tribunal: 51, indeterminate: false },
    { id:13232, descricao:  'JME/RS - 2ª Auditoria', tribunal: 51, indeterminate: false },
    { id:13234, descricao:  'JME/RS - Auditoria de Santa Maria', tribunal: 51, indeterminate: false },
    { id:13235, descricao:  'JME/RS - Auditoria de Passo Fundo', tribunal: 51, indeterminate: false },
    { id:15661, descricao: 'JME/SP - 1ª Auditoria', tribunal: 11, indeterminate: false },
    { id:17970, descricao: 'JME/SP - 2ª Auditoria', tribunal: 11, indeterminate: false },
    { id:15662, descricao: 'JME/SP - 3ª Auditoria', tribunal: 11, indeterminate: false },
    { id:15663, descricao: 'JME/SP - 4ª Auditoria', tribunal: 11, indeterminate: false },
    { id:29004, descricao: 'JME/SP - 5ª Auditoria', tribunal: 11, indeterminate: false },
    { id:29005, descricao: 'JME/SP - 6ª Auditoria', tribunal: 11, indeterminate: false },
	{ id:32693, descricao: 'JMU - 1ª Auditoria da 1ª CJM', tribunal: 61, indeterminate: false },
	{ id:32694, descricao: 'JMU - 2ª Auditoria da 1ª CJM', tribunal: 61, indeterminate: false },
	{ id:32695, descricao: 'JMU - 3ª Auditoria da 1ª CJM', tribunal: 61, indeterminate: false },
	{ id:32696, descricao: 'JMU - 4ª Auditoria da 1ª CJM', tribunal: 61, indeterminate: false },
    { id:32697, descricao: 'JMU - 1ª Auditoria da 2ª CJM', tribunal: 61, indeterminate: false },
    { id:32698, descricao: 'JMU - 2ª Auditoria da 2ª CJM', tribunal: 61, indeterminate: false },
	{ id:32699, descricao: 'JMU - 1ª Auditoria da 3ª CJM', tribunal: 61, indeterminate: false },
	{ id:32700, descricao: 'JMU - 2ª Auditoria da 3ª CJM', tribunal: 61, indeterminate: false },
	{ id:32701, descricao: 'JMU - 3ª Auditoria da 3ª CJM', tribunal: 61, indeterminate: false },
    { id:32702, descricao: 'JMU - Auditoria da 4ª CJM', tribunal: 61, indeterminate: false },
    { id:32703, descricao: 'JMU - Auditoria da 5ª CJM', tribunal: 61, indeterminate: false },
    { id:32704, descricao: 'JMU - Auditoria da 6ª CJM', tribunal: 61, indeterminate: false },
    { id:32705, descricao: 'JMU - Auditoria da 7ª CJM', tribunal: 61, indeterminate: false },
    { id:32706, descricao: 'JMU - Auditoria da 8ª CJM', tribunal: 61, indeterminate: false },
    { id:32707, descricao: 'JMU - Auditoria da 9ª CJM', tribunal: 61, indeterminate: false },
    { id:32708, descricao: 'JMU - Auditoria da 10ª CJM', tribunal: 61, indeterminate: false },
    { id:32709, descricao: 'JMU - 1ª Auditoria da 11ª CJM', tribunal: 61, indeterminate: false },
	{ id:32710, descricao: 'JMU - 2ª Auditoria da 11ª CJM', tribunal: 61, indeterminate: false },
	{ id:32711, descricao: 'JMU - Auditoria da 12ª CJM', tribunal: 61, indeterminate: false },
]);

export default TribunaisEnum;
